name: CI

on:
  push:
    branches:
      - 'master'
    tags:
      - v*

env:
  CARGO_INCREMENTAL: 0
  RUST_CACHE_VERSION: v1

jobs:
  release_linux:
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        include:
          - ghimage: ubuntu-24.04
            os: windows
            arch: i686
            target: i686-pc-windows-gnu

    permissions:
      contents: write

    runs-on: ${{ matrix.ghimage }}

    steps:
      - uses: actions/checkout@v5.0.0
        with:
          submodules: true

      - if: ${{ matrix.target == 'i686-pc-windows-gnu' }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc-mingw-w64-i686
          rustup target add i686-pc-windows-gnu

      - uses: Swatinem/rust-cache@v2.8.1
        with:
          prefix-key: ${{ env.RUST_CACHE_VERSION }}-rust

      - name: Build
        env:
          TARGET: ${{ matrix.target }}
        run: |
          cargo build --release --target $TARGET

  clippy_and_test:
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        include:
          - ghimage: ubuntu-24.04
            dockerarch: linux/amd64
            mcarch: amd64

    permissions:
      packages: write
      checks: write
      contents: read
      deployments: write

    runs-on: ${{ matrix.ghimage }}

    steps:
      - uses: actions/checkout@v5.0.0

      - name: Get Rust toolchain
        id: toolchain
        run: |
          awk -F'[ ="]+' '$1 == "channel" { print "toolchain=" $2 }' rust-toolchain >> "$GITHUB_OUTPUT"

      - name: install clippy
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ steps.toolchain.outputs.toolchain }}
          components: clippy

      - name: cache dependencies
        uses: Swatinem/rust-cache@v2.8.1
        with:
          prefix-key: ${{ env.RUST_CACHE_VERSION }}-rust

      - name: clippy check
        uses: yanorei32/action-clippy@50412b135153ebee7d4b8a5b868c4defdc663683
        with:
          reporter: github-check

      - name: unit test
        run: |
          cargo test --no-run --locked
          cargo test

      - name: release build
        run: cargo build --release

