name: Review

on:
  pull_request:
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/review.yml'


env:
  CARGO_INCREMENTAL: 0

jobs:
  rust:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5.0.0

      - run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc-mingw-w64-i686
          rustup target add i686-pc-windows-gnu

      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          components: clippy
          override: true

      - name: cache dependencies
        uses: Swatinem/rust-cache@v2.8.1

      - name: clippy check
        uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - name: compile for unit test
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test
          args: --no-run --locked

      - name: unit test
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test
